<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Authentication\" />
    <Folder Include="Email\" />
    <Folder Include="FileStorage\" />
    <Folder Include="ExternalServices\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Tesseract" Version="5.2.0" />
    <PackageReference Include="PdfPig" Version="0.1.9" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.10" />
  </ItemGroup>

  <ItemGroup>
    <None Update="tessdata\eng.traineddata">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BGVSystem.Application\BGVSystem.Application.csproj" />
    <ProjectReference Include="..\BGVSystem.Shared\BGVSystem.Shared.csproj" />
  </ItemGroup>

</Project>
